### ISSUE TITLE
[website] update composer command to use 1.0.*@dev in website

### ISSUE THREAD

**Issue by samsonasik** [Bee-Lab/bowerphp#100]
I'm not sure if it is the right place to report issue of instruction command installation in website that said : 
```shell
$ composer require "beelab/bowerphp 0.1.*@alpha"
```
When I try to load some assets, I got error in my local : 
```shell
$ vendor/bin/bowerphp install
bower selectize#0.8.5      
bower selectize#v0.8.5    install
Version 0.3.x not found.
```
So, I try to update with : 
```shell
$ composer require "beelab/bowerphp 1.0.*@dev"
```
and it works.
So, I think the website for command installation instruction need to be updated.

**Comment by garak** [comment]
I just updated webiste.
Thank you
