### ISSUE TITLE
Impossible to save a package if installed previously

### ISSUE THREAD

**Issue by mikeSimonson** [Bee-Lab/bowerphp#104]
If you want to save a package that you have already installed with ```bowerphp install jquery-address```.
It will fail because there is a check for that in [bowerphp.php line 100](https://github.com/Bee-Lab/bowerphp/blob/master/src/Bowerphp/Bowerphp.php#L100).

Not sure what the best approach is in this case ?

**Comment by garak** [comment]
Bower does just the same: if a package is already installed, it's not installed again.

**Comment by mikeSimonson** [comment]
It's right that it does not install it again but it should add it in the bower.json

**Comment by garak** [comment]
No. There is no implicit adding in bower.json, you need to use ``-S`` flag

**Comment by mikeSimonson** [comment]
I know.
The problem is that it won't add it to the bower.json when using ```bowerphp install -S jquery-address ```, if that package has already been installed previously using ```bowerphp install jquery-address```.

The bug is that the -S option doesn't work if the package is already installed.

Maybe the easiest/cleanest fix is just to check for the -S option before to try to install ?

**Comment by mikeSimonson** [comment]
The problem is that it returns [on line 104](https://github.com/Bee-Lab/bowerphp/blob/master/src/Bowerphp/Bowerphp.php#L104) if the package is already installed with the same version. That's before it's checking for the -S option [on line 116](https://github.com/Bee-Lab/bowerphp/blob/master/src/Bowerphp/Bowerphp.php#L116).

**Comment by mikeSimonson** [comment]
I have to check but I also have the impression that the version in bower.json file won't be updated if a package is updated.

**Comment by mikeSimonson** [comment]
Well my remark about the update command make no sense. As it will only update depending on the version requirements.
