### ISSUE TITLE
help command display false information

### ISSUE THREAD

**Issue by mikeSimonson** [Bee-Lab/bowerphp#108]
On the last line the help command say that to show the list of available command we should use the list command, which is wrong. It's the list-commands that implement that feature. I didn't found were to configure that.

**Comment by garak** [comment]
That's a Symfony functionality. We need to override it somehow.

**Comment by mikeSimonson** [comment]
As far as I understand we just need to copy/paste and adapt this class ```Symfony\Component\Console\Command\HelpCommand;```.
It's in the [application file](https://github.com/Bee-Lab/bowerphp/blob/master/src/Bowerphp/Console/Application.php#L97).

**Comment by garak** [comment]
Why copy/paste? Don't you think that extending it would be better?

**Comment by mikeSimonson** [comment]
Yeah maybe extending is a bit less ugly.
