### ISSUE TITLE
bowerphp installing wrong package version

### ISSUE THREAD

**Issue by lrlopez** [Bee-Lab/bowerphp#111]
Hi,

I've just added Bowerphp to my Symfony project but I'm having some problems to get `jquery` installed.

When my project depends on `jquery#2.*"` or when I run `php vendor/beelab/bowerphp/bin/bowerphp install "jquery#2.*"`, bowerphp seems to install latest master despite I stated `2.*`. It even prints into console that the version to be downloaded is 2.1.3 but the uncompressed archive is not right.

Inside `vendor/jquery` there is no `dist/` folder. Also, `bower.json` contains this:
```json
{
  "name": "jquery",
  "version": "3.0.0-pre",
  "main": "dist/jquery.js",
  "license": "MIT",
  "ignore": [
    "**/.*",
    "build",
    "speed",
    "test",
    "*.md",
    "AUTHORS.txt",
    "Gruntfile.js",
    "package.json"
  ],
  "keywords": [
    "jquery",
    "javascript",
    "library"
  ]
}
```

This matches current `master` branch in jquery/jquery repository, but not the latest 2.1.3 tag.

Original bower seems to work through.

Am I doing something wrong? Other packages seem to install the right way, but not this one.

**Comment by garak** [comment]
Looks like there is a problem with [php-github-api](https://github.com/KnpLabs/php-github-api).
I tried ``bowerphp install jquery#2.* -vvv`` and I see that php-github-api tries to fetch https://api.github.com/repos/jquery/jquery/zipball?ref=2.1.3, but such URL returns the master version of package.
The correct URL should be https://api.github.com/repos/jquery/jquery/zipball/2.1.3, but a this point I don't know why php-github-api it's using an alternate URL (I would like to be sure it's an actual bug before opening an issue on them)

**Comment by lrlopez** [comment]
Thanks @garak for pointing out the problem. I've just created a PR that fixes the API call mismatch, I hope it gets reviewed soon.
