### ISSUE TITLE
Some dependencies are not installed

### ISSUE THREAD

**Issue by judgedim** [Bee-Lab/bowerphp#119]
I think related with  bug #82 

"version": "v0.2.4-alpha"

```javascript
{
    "name": "TestProject",
    "dependencies": {
        "jqueryui": "1.10.4",
        "jquery-file-upload": "9.9.*",
        "jqgrid": "4.8.2"
    }
}
```

![selection_610](https://cloud.githubusercontent.com/assets/3140807/7268597/c9cfa9d8-e8d3-11e4-8384-d4d666009e44.png)

When I do a 'bower install' with the node bower, it correctly finds *jquery-file-upload* and installs it.

**Comment by garak** [comment]
Works for me.
Be sure to use the latest dev-master package of bowerphp

**Comment by judgedim** [comment]
unfortunately, it didn't help

![selection_612](https://cloud.githubusercontent.com/assets/3140807/7270706/dc008452-e8e6-11e4-94c4-872882718d85.png)

**Comment by garak** [comment]
Can you paste the output of your bowerphp install command?

**Comment by judgedim** [comment]
bower jquery-ui#1.10.4     
bower jquery-ui#1.10.4         install
bower jquery#>=1.6         
bower jquery#2.1.3             install
bower jquery-file-upload#9.9.*
bower jquery-file-upload#9.9.3    install
bower blueimp-tmpl#>=2.5.4 
bower blueimp-tmpl#2.5.4       install
bower blueimp-load-image#>=1.13.0
bower blueimp-load-image#1.13.0    install
bower blueimp-canvas-to-blob#>=2.1.1
bower blueimp-canvas-to-blob#2.1.1    install
bower jqgrid#4.8.2         
bower jqgrid#v4.8.2            install
bower jquery-ui#>=1.7.0        install
bower requirejs#2.1.8      
bower requirejs#2.1.8          install
bower require-css#0.1.7    
bower require-css#0.1.7        install

**Comment by garak** [comment]
OK, I found the problem: these packages ignore everything (having ``"/*.*"`` inside their ``ignore`` key).
So, we need to force entries in ``main`` to be not ignored, even if they are in the ``ignore`` pattern.

**Comment by garak** [comment]
@judgedim I released a new tag
