### ISSUE TITLE
Fatal error: DialogHelper is deprecated

### ISSUE THREAD

**Issue by gms8994** [Bee-Lab/bowerphp#122]
Trying to run `./vendor/bin/bowerphp`, I get the following error:

    Fatal error: Uncaught exception 'ErrorException' with message
    '"Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be
    removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.' in
    vendor/symfony/console/Helper/DialogHelper.php on line 34

**Comment by garak** [comment]
Can you post the relevant parts of ``composer show -i`` command output? For "relevant" I mean at least Symfony version and bowerphp version.

**Comment by gms8994** [comment]
Wasn't sure which Symfony info you wanted, so I included it all.

```
beelab/bowerphp                       v0.3.3-beta        An implementation of bower in PHP
symfony/console                       v2.7.0             Symfony Console Component
symfony/css-selector                  v2.7.0             Symfony CssSelector Component
symfony/debug                         v2.7.0             Symfony Debug Component
symfony/dom-crawler                   v2.7.0             Symfony DomCrawler Component
symfony/event-dispatcher              v2.7.0             Symfony EventDispatcher Component
symfony/filesystem                    v2.7.0             Symfony Filesystem Component
symfony/finder                        v2.7.0             Symfony Finder Component
symfony/http-foundation               v2.7.0             Symfony HttpFoundation Component
symfony/http-kernel                   v2.7.0             Symfony HttpKernel Component
symfony/process                       v2.7.0             Symfony Process Component
symfony/routing                       v2.7.0             Symfony Routing Component
symfony/translation                   v2.7.0             Symfony Translation Component
symfony/var-dumper                    v2.7.0             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v2.7.0             Symfony Yaml Component
```

**Comment by garak** [comment]
Upgrading to Symfony 2.7.1 will fix your problem. Thank you.

**Comment by gms8994** [comment]
garak, I understand that. But this issue was introduced by installing bowerphp. Shouldn't the version number for Symfony be adjusted in bowerphp's composer.json?

**Comment by garak** [comment]
Our currently requirement is for Symfony ~2.3. We cannot support minor versions of Symfony.
