### ISSUE TITLE
Not view the package name, if package not found.

### ISSUE THREAD

**Issue by ZhukV** [Bee-Lab/bowerphp#123]
Not view the package name in console view, if package not found.

As example:

File `bower.json`:

```json
{
    "name": "FooBar",
    "private": true,
    "dependencies": {
        "bootstrap": "~3.3.1",
        "datatables": "~1.10.4",
        "datatables-plugins": "~1.0.1"
    }
}
```

And the package `datatables-plugins` not found.

Console output:

```bash
$ ./bin/bowerphp install
Not Found

```

**Comment by clue** [comment]
Interesting, this should have been addressed via #117?

What version are you testing this with?

**Comment by garak** [comment]
@ZhukV can you provide info about used version? Otherwise, I'll close this.

**Comment by garak** [comment]
No feedback
