### ISSUE TITLE
BOWERPHP_TOKEN as Composer variable

### ISSUE THREAD

**Issue by rvanlaak** [Bee-Lab/bowerphp#127]
Would the [`Composer environment variables`](https://getcomposer.org/doc/03-cli.md#environment-variables) allow us to define `BOWERPHP_TOKEN`? 

That would mean we can do the following:

```
"scripts": {
    // ...
    "post-install-cmd": [
        "bin/bowerphp install",
        // ...
    ],
    "post-update-cmd": [
       "bin/bowerphp install",
        // ...
   ]
},
"config": {
    "bin-dir": "bin",
    "BOWERPHP_TOKEN": "<token>"
},
```
Or is this the wrong interpretation of the composer environment variables?

Next to that, `composer install` also outputs an empty error message when `bowerphp install` is executed via `post-install-cmd`.

**Comment by garak** [comment]
I'm not sure about composer environment variable, I think it should work (but if doesn't, it's not a problem of bowerphp).
You can try to set "bin/bowerphp install -vvv" in your "post-install-cmd" and see what it's happening.
Let me know.

**Comment by Rvanlaak** [comment]
Will do :+1:

**Comment by Rvanlaak** [comment]
`bin/bowerphp install -v` is verbose enough to output the error message :+1: 

    You have reached GitHub hour limit! Actual limit is: 60

Including the token in the composer.json `config` unfortunately does not set the environment variable.

**Comment by garak** [comment]
Reading the docs, composer allows setting only for **its** environment variabiles, not for *any* environment variable.
You should set ``BOWERPHP_TOKEN`` elsewhere.

**Comment by rvanlaak** [comment]
Yes also found out that, :+1: for closing this one
