### ISSUE TITLE
bowerphp doesn't install dependencies for GitHub packages

### ISSUE THREAD

**Issue by miztroh** [Bee-Lab/bowerphp#128]
I'm using this in an environment where I don't have rights to install node.  In that way, it's been a great find.  Thanks!

Bower fetches a GitHub package and then checks its bower.json for any dependencies, then goes and fetches those packages and their dependencies, etc.  BowerPHP doesn't do that.

For example: `bowerphp install --save https://github.com/PolymerElements/paper-elements.git#latest`

That command should cause BowerPHP to grab the specified package (it does) and then recursively grab its dependencies (it doesn't).  Without that functionality, I'll have to manually install loads of dependencies individually.

Here's a link to that repo's bower.json.  As you can see, this one package has 30 or so dependencies.

https://github.com/PolymerElements/paper-elements/blob/master/bower.json

**Comment by garak** [comment]
I just tried and it looks like there is a problem with a version constraint. The error I get using ``bowerphp search paper-elements`` is ``Criteria PolymerElements/paper-badge#^1.0.0 is not valid.``.
I plan to remove soon the current library for semver with a better one.

**Comment by miztroh** [comment]
@garak Polymer hasn't added most of their individual elements to the bower repository.  That's why it's so crucial (for me) that GitHub installs Just Work™.
