### ISSUE TITLE
Cannot install package without version

### ISSUE THREAD

**Issue by ibcs01** [Bee-Lab/bowerphp#129]
Hi,

First of all, thanks for writing this great package.
I am using it for a few weeks now, and today I came across an issue that I cannot get solved.
I might overlook something, and i hope someone can point me in a direction.

Problem is that i cannot install a package called soundmanager2.
Reason is that the package does not has any versions defined.

When i search for the package, i get these results:

root@dev:/srv/www/site# bin/bower search soundmanager2
#!/usr/bin/env php
Search results:

    soundmanager git://github.com/scottschiller/SoundManager2.git
    soundmanager2 git://github.com/scottschiller/SoundManager2.git
    angular-soundmanager2 git://github.com/perminder-klair/angular-soundmanager2.git
    backbone.soundmanager2 git://github.com/audiosocket/backbone.soundmanager2.git
    armory-blrrtstrap-soundmanager2 git://github.com/psirenny/armory-blrrtstrap-soundmanager2.git
    soundmanager2-297a20140901 git://github.com/akarca/SoundManager2-1.git
    soundmamager2 git://github.com/scottschiller/SoundManager2.git

I then go ahead and install soundmanager2, the latest release:

root@dev:/srv/www/site# bin/bower install soundmanager2#latest
#!/usr/bin/env php
Cannot find package soundmanager2 version latest.

If i leave out the version part, i still have no success:

root@dev:/srv/www/site# bin/bower install soundmanager2
#!/usr/bin/env php
Cannot find package soundmanager2 version *.

Is there some way i can get this package installed?
In this case it would be sufficient if it just uses the latest commit.

Any help would be appreciated.
Thanks!

**Comment by garak** [comment]
This is a know issue, see #113 and #128 
We still need to implement installation from a git URL or http URL.
If you want to implement such feature, feel free to open a pull request.

**Comment by ibcs01** [comment]
OK, thank you.
