### ISSUE TITLE
enhance handling of installed packages

### ISSUE THREAD

**Issue by garak** [Bee-Lab/bowerphp#13]
We currently establish if a package is installed by looking for its bower.json file.
This is ugly, and bower uses a different approach (some packages have bower.json in "ignore").
We must investigate how bower handles this and try to replicate it.

**Comment by gustavohenke** [comment]
There's a `.bower.json` file. It holds all necessary info about the cloned package.

**Comment by gustavohenke** [comment]
I mean, that may not be the true way to check the package installation status, but it's more reliable... because that file is hidden in Unix OSs :ok_hand:

**Comment by garak** [comment]
This has been fixed some time ago. Now we rely on ``.bower.json``
