### ISSUE TITLE
How maintained is this project?

### ISSUE THREAD

**Issue by Swader** [Bee-Lab/bowerphp#132]
@garak is this project still being maintained? We're big fans of it over [at SitePoint](http://www.sitepoint.com/bower-vs-bowerphp/) and I was wondering if there's any way we can help with keeping it alive and kicking, besides contributing directly. Is beelab actively interested in taking it further? I ask because the main Bower project is kind of dead, but BowerPHP is still incredibly useful, to me at least - I use it regularly.

**Comment by garak** [comment]
Hello @Swader and thanks for your interest.
While activity on this project is not heavy, we'd like keep supporting and developing it.
I'd like to release a non-beta version, but a couple of issues keep me from doing it: see #118, #128 and #113.
I can tag such issues with a milestone, to make this explicit.
Anyway, I see that working on that issue would likely require a big refactoring in how we handle dependencies right now. Being this a side project, I'm not sure to get enough time to invest in this. Here can come your help, if you mind to work on that.

**Comment by Swader** [comment]
@garak I'll try and take a look, get it some more exposure at the very least.
