### ISSUE TITLE
Is Symfony 3 support planned?

### ISSUE THREAD

**Issue by st0at** [Bee-Lab/bowerphp#133]
Hi,

I just wanted to know if the support for Symfony 3 is planned. Because now I cannot install it on Symfony 3:
composer require beelab/bowerphp:1.0.*@dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for beelab/bowerphp 1.0.*@dev -> satisfiable by beelab/bowerphp[1.0.x-dev].
    - Conclusion: remove symfony/symfony v3.0.1
....

Thanks

**Comment by Capenus** [comment]
See #131

**Comment by garak** [comment]
There an active PR (the one mentioned above)
