### ISSUE TITLE
Private Repository

### ISSUE THREAD

**Issue by itstueben** [Bee-Lab/bowerphp#140]
Hey we use a private Repository hostet on a local Server. (https://github.com/Hacklone/private-bower)
With npm Bower Installation it works fine. In bowerphp the packges wont find. If we take a offical packge it works fine. Anyone knows bowerphp support private repository?
Our repositorys are hostet in SVN! Can SVN be the problem?

**Comment by garak** [comment]
I'm sorry but the current implementation only works with git. As you can see [here](https://github.com/Bee-Lab/bowerphp/tree/master/src/Bowerphp/Repository), there is only a `GitRepository` class.
Feel free to open a PR implementing a possible `SvnRepository` class.
