### ISSUE TITLE
lock file

### ISSUE THREAD

**Issue by kbca** [Bee-Lab/bowerphp#141]
If we want to use bowerphp to manage our dependencies and install some of them, we have to commit all the files of the dependencies because bowerphp doesn't generate a .lock file saving the libs which were downloaded. So, if somebody wants to contribute to your project and you didn't committed the dependencies, this user can't know which dependencies you're using.

It would be great that instead of commiting all dependencies libs installed with bower, it generate a bower.lock (as example) and bower.json, like bower from node does, saving the dependencies the project is using and also the latest version downloaded

**Comment by garak** [comment]
We're just re-implementing bower here.
If bower ever implements such feature, we could do it as well.
See see https://github.com/bower/bower/issues/505
