### ISSUE TITLE
Getting 404's on all packages for install and update

### ISSUE THREAD

**Issue by simplimation** [Bee-Lab/bowerphp#142]
When I install or update packages, they all return 404 from Github. Looks like Github changed the path to package.json?

> bowerphp install superslides
Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/nicinabox/superslides/master/package.json

> bowerphp update superslides
Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/nicinabox/superslides/master/package.json

> bowerphp search superslides
Search results:
    superslides https://github.com/nicinabox/superslides.git

> wget https://github.com/nicinabox/superslides/master/package.json
--2016-04-29 10:19:40--  https://github.com/nicinabox/superslides/master/package.json
Resolving github.com... 192.30.252.129
Connecting to github.com|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-29 10:19:40 ERROR 404: Not Found.

**Comment by piotr-zuralski** [comment]
is should be https://github.com/nicinabox/superslides/blob/master/package.json for the first one

**Comment by garak** [comment]
Just tried with latest bowerphp version and `bowerphp install superslides` works as expected (it installs superslides)
