### ISSUE TITLE
Question: Shell_execute PHP function vs BowerPHP

### ISSUE THREAD

**Issue by myuseringithub** [Bee-Lab/bowerphp#149]
Whats the cons and pros of using any of these two options. Other than the need of Node.js to be installed when using shell_execute. 

For using Bower on Node.js, what's the recommended option if I want to install/update packages using PHP script ? e.g. building a web UI to control Bower packages, where a PHP endpoint is used to achieve this task.

Thanks

**Comment by garak** [comment]
I'm not sure to understand your question... if you can rely on the original Bower, you don't need anything else, not BowerPHP, nor any other PHP script.
