### ISSUE TITLE
Why bower don't have rate limit, but bowerphp does?

### ISSUE THREAD

**Issue by demil** [Bee-Lab/bowerphp#152]
Why bower don't have rate limit, but bowerphp does?

**Comment by garak** [comment]
Everyone has a limit when accessing github APIs, also Bower. You can check it easily by looking into Bower project issues.

**Comment by demil** [comment]
but i can easily use bower and i have never hit rate limit, but on bowerphp there was hit immediately.

**Comment by garak** [comment]
This is explained in the README.
