### ISSUE TITLE
[Release] Website has 0.5 release phar, but github and packagist don't

### ISSUE THREAD

**Issue by diimpp** [Bee-Lab/bowerphp#153]
Hi,

as topic says, github missing 0.5 release for some reason.

Cheers,
Dmitri.

**Comment by garak** [comment]
It was a typo in website, it's fixed now.
Thank you

**Comment by diimpp** [comment]
https://bowerphp.org/bowerphp.phar

Now returns 404, note, that previous available phar build showed 0.5 version as well.

**Comment by garak** [comment]
Fixed now. Thanks again
