### ISSUE TITLE
The bowerphp.org domain seems to be expired

### ISSUE THREAD

**Issue by peter279k** [Bee-Lab/bowerphp#155]
The bowerphp.org domain is not available now. 
Please fix it. Thanks.

**Comment by garak** [comment]
Ping @maurodalatri

**Comment by peter279k** [comment]
Unfortunately, the domain still is not available. What happen ?

**Comment by indrakaw** [comment]
Oh no. Time to stick with GitHub Pages.

You can check the site via web archive at http://web.archive.org/web/bowerphp.org tbh

**Comment by garak** [comment]
Domain should be trasferred to @maurodalatri 
Meanwhile, you can force your local dns to resolve it on 217.160.176.118

**Comment by samayo** [comment]
@garak  What is with the IP? it redirects to a different site. I see no content related to bowerPHP.

**Comment by garak** [comment]
You can't recall that IP directly. You need to force your local domain resolver to resolve bowerphp.org to it.
See https://en.wikipedia.org/wiki/Hosts_(file) for more info.

**Comment by fridde** [comment]
Can you please remove the bowerphp.org link from the Readme?
