### ISSUE TITLE
RuntimeException - Could not find .../Guzzle/Http/Resources/cacert.pem

### ISSUE THREAD

**Issue by rdmendo** [Bee-Lab/bowerphp#157]
[RuntimeException]
bowerphp.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem

PS: Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by garak** [comment]
`guzzle/guzzle` is a dependency of `knplabs/github-api`.
I tried to upgrade `knplabs/github-api` to `2.*`, but it changed a lot since `1.*` and it's a mess.

**Comment by garak** [comment]
I'm closing this since I cannot reproduce. I just tried to compile from source (using `bin/console compile 1`) and .pem file is there
