### ISSUE TITLE
Add a composer script

### ISSUE THREAD

**Issue by akovalyov** [Bee-Lab/bowerphp#162]
Hi,
First of all - thank you for this lib, it is really cool.
I have a simple proposal - can a simple composer script be shipped with the lib? Then with one simple command one is able to install everything (of course after adding it to scripts section in composer.json).
 
What do you think?

**Comment by garak** [comment]
Which kind of script?

**Comment by akovalyov** [comment]
@garak https://getcomposer.org/doc/articles/scripts.md

In this case it will be a simple class with one public static method, which will install bower assets after composer dependencies are installed.

**Comment by garak** [comment]
Considering that you can use scripts like this one (taken just from the link you suggested) `"php -r \"copy('config/local-example.php', 'config/local.php');\""`, I guess that you don't need anything more of what is already available, e.g. a binary to execute (`bowerphp` in our case)

**Comment by akovalyov** [comment]
@garak well, I agree. Probably I am too used to Symfony script handlers.
