### ISSUE TITLE
Trying to install cycle js

### ISSUE THREAD

**Issue by ace411** [Bee-Lab/bowerphp#164]
Hello there, I am trying to install the package cycle js and failing miserably. I keep getting the error message:
```
Client error response
[status code] 404
[reason phrase] Not Found
[url] https://github.com/staltz/cycle/master/package.json
```
A little help would be greatly appreciated.

**Comment by garak** [comment]
It works for me using latest bowerphp version

**Comment by ace411** [comment]
Should I add bowerphp to my path?

**Comment by garak** [comment]
I'm not sure to understand how the path could be related to this issue...

**Comment by ace411** [comment]
What do you think the problem is?

**Comment by garak** [comment]
You're using an old version of bowerphp

**Comment by ace411** [comment]
Alright. Thank you.

**Comment by ace411** [comment]
I'll get the latest version as soon as possible.
