### ISSUE TITLE
how to move it in your $PATH (e.g. /usr/local/bin)

### ISSUE THREAD

**Issue by hanxzi** [Bee-Lab/bowerphp#165]
$composer require beelab/bowerphp
beelab/bowerphp                   v0.4.0  An implementation of bower in PHP
so,how to move to $path

**Comment by garak** [comment]
That makes sense only if you downloaded the phar (or if you built it yourself).

**Comment by hanxzi** [comment]
thanks

**Comment by garak** [comment]
You're welcome
