### ISSUE TITLE
Update Registry

### ISSUE THREAD

**Issue by jalandis** [Bee-Lab/bowerphp#166]
Bower has moved their registry.  This redirect is breaking a legacy application I support.

```
Cannot fetch registry info for package bootstrap from search registry ([curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://registry.bower.io/packages/bootstrap).
```
[Bower Registry Commit](https://github.com/bower/bower/commit/6500b421ce02abba9259e08f8b31597984c3c83d
)
[Twitter Announcement](https://twitter.com/bower/status/908359136601133056
)

**Comment by garak** [comment]
Fixed in #167 
Thanks!
