### ISSUE TITLE
API rate limit with GitHub

### ISSUE THREAD

**Issue by sstok** [Bee-Lab/bowerphp#49]
Please consider using the KnpLabs GitHub API so you can authenticate, create a token and not hit the API rate limit.

This is also done by Composer when the rate limit is hit.

**Comment by Rvanlaak** [comment]
Would the [`Composer environment variables`](https://getcomposer.org/doc/03-cli.md#environment-variables) allow us to define `BOWERPHP_TOKEN`? 

That would mean we can do the following:

```
"scripts": {
        // ...
        "post-install-cmd": [
            "bin/bowerphp install",
            // ...
        ],
        "post-update-cmd": [
            "bin/bowerphp install",
            // ...
        ]
    },
    "config": {
        "bin-dir": "bin",
        "BOWERPHP_TOKEN": "<token>"
    },
```
Or is this the wrong interpretation of the composer environment variables?
