### ISSUE TITLE
Handling renamed git repo

### ISSUE THREAD

**Issue by varoot** [Bee-Lab/bowerphp#54]
BowerPHP doesn't handle the case when a repo is renamed on GitHub

For example, the package "jquery-hammerjs" returns "git://github.com/EightMedia/jquery.hammer.js.git"
(Check out https://bower.herokuapp.com/packages/jquery-hammerjs)

However, "EightMedia" has been renamed to "hammerjs" so https://github.com/EightMedia/jquery.hammer.js redirects to https://github.com/hammerjs/jquery.hammer.js but the API call of https://api.github.com/repos/EightMedia/jquery.hammer.js returns a 404 instead.

I believe Bower.js doesn't use GitHub API so it was able to find the correct repo.

**Comment by garak** [comment]
Tag v0.3.2-beta contains the fix for this issue.
