### ISSUE TITLE
Add argument "register"

### ISSUE THREAD

**Issue by julkue** [Bee-Lab/bowerphp#57]
After running `bower register xxx xxx` I get the following error:
  [InvalidArgumentException]
  Command "register" is not defined.

This is a important functionality because bower does not have all packages from github!

**Comment by mefiblogger** [comment]
:+1:

**Comment by surikat** [comment]
+1

**Comment by garak** [comment]
Feel free to open a PR

**Comment by julmot** [comment]
@garak I've already switched to the origiball one as of missing arguments
