### ISSUE TITLE
version problem 

### ISSUE THREAD

**Issue by mhf-ir** [Bee-Lab/bowerphp#65]
Version 1.2.\* not found.

```
 // ...
  "dependencies": {
    "angular": "1.2.*",
    "angular-route": "1.2.*",
 // ...
```

This bower.json work on node version of bower.

**Comment by shyaken** [comment]
![image](https://cloud.githubusercontent.com/assets/158163/5691048/71f5ed72-98e6-11e4-9c2e-39ebd5c36b7e.png)
I added BOWER_TOKEN on windows, still get GitHub hour limit. I already restarted cmd. why you don't just add a config to bower.json?

**Comment by garak** [comment]
We can't alter the syntax of bower.json, it must be compatible with official bower one.
Anyway, try with ``php -r 'var_dump(getenv("BOWERPHP_TOKEN"));'`` and see the results, it should be something like ``string(40) "912blablabla..."``
