### ISSUE TITLE
Tag names

### ISSUE THREAD

**Issue by mnapoli** [Bee-Lab/bowerphp#93]
Hi there,

We are using BowerPHP in [Couscous](https://github.com/CouscousPHP/Couscous) and we noticed issues when people install Couscous with Composer.

The reason for that seems that we require `"beelab/bowerphp": "0.1.*@alpha"` and with a default config Composer doesn't like alpha versions. Here is a part of the error message:

> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

So would it be possible to tag your releases without the `-alpha` suffix? In theory in SemVer `0.x` versions are considered pre-releases so I think have `-alpha` is just redundant and only creates problems with Composer.

Cheers and thanks for the good stuff!

**Comment by garak** [comment]
I know that I'm arriving really late, but this project now has a non-beta tag.

**Comment by mnapoli** [comment]
Thank you, in the meantime we have switched to Bower.
